name: droplet-template

services:
  postgres:
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: pgvector/pgvector:pg17
    ports:
      - 65432:5432
    restart: unless-stopped
    stop_grace_period: 3s
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - droplet-template-network

  rails-app:
    container_name: rails-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3600:3000
    volumes:
      - .:/rails
      - /rails/node_modules
      - /rails/.yarn
    depends_on:
      - postgres
    environment:
      - RAILS_ENV=development
      - RUBY_YJIT_ENABLE=1
      - RAILS_LOG_TO_STDOUT=1
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/droplet_template_development
    command: |
      bash -c "
        rm -f tmp/pids/server.pid && \
        bundle exec rails db:prepare && \
        bin/rails server -b 0.0.0.0 -p 3000
      "
    tty: true
    stdin_open: true
    networks:
      - droplet-template-network

volumes:
  postgres: {}

networks:
  droplet-template-network:
    driver: bridge
