default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: droplet_template_development

test:
  <<: *default
  database: droplet_template_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
  # Define primary database for solid_queue
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>